name: Bug Report
description: File a bug report
title: "[Bug]: <set a title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @discord.user
    validations:
      required: false

  - type: textarea
    id: syntax
    attributes:
      label: Syntax you used
      description: Please copy and paste the syntax you use for create the bug. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened! Explain with more details please"
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      value: "V0.4"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What social media are you seeing the problem on?
      multiple: true
      options:
        - YouTube
        - TikTok
        - Dailymotion 🤡

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: todolist
    attributes:
      label: To Do List [DEV ONLY]
      description: Only dev can modify, if your are not dev then don't touch it!
      options:
        - label: To do 1
        - label: To do 2
          required: true
