name: Bug Report
description: Describe your bug report!
title: "[Bug] | <set a title>"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @discord.user
    validations:
      required: false

  - type: textarea
    id: syntax
    attributes:
      label: Syntax you used
      description: Please copy and paste the syntax you used to create the bug.
      placeholder: Tell the syntax you used to generate the bug.
      render: shell

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened! Explain with more details please"
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      value: "0.7 (latest)"
    validations:
      required: true

  - type: dropdown
    id: browsers_1
    attributes:
      label: browsers
      description: What social media are you seeing the problem on?
      options:
        - "YouTube"
        - "TikTok"
        - "Dailymotion 🤡"
        - "Others"
    validations:
      required: true
  - type: dropdown
    id: browsers_2
    attributes:
      label: browsers
      description: Other social media with this problem?
      options:
        - "No"
        - "YouTube"
        - "TikTok"
        - "Dailymotion 🤡"
        - "Others"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell